version: '3'

services:
  ent-gen:
    container_name: ent-gen
    build:
      context: ../../src
      dockerfile: ../docker/ent/Dockerfile
    volumes:
      - ../../src/infrastructure/ent:/go/src/github.com/Doer-org/google-cloud-challenge-2022/server/src/infrastructure/ent
    tty: true