// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Doer-org/google-cloud-challenge-2022/infrastructure/ent/authstates"
	"github.com/Doer-org/google-cloud-challenge-2022/infrastructure/ent/predicate"
)

// AuthStatesQuery is the builder for querying AuthStates entities.
type AuthStatesQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	inters     []Interceptor
	predicates []predicate.AuthStates
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AuthStatesQuery builder.
func (asq *AuthStatesQuery) Where(ps ...predicate.AuthStates) *AuthStatesQuery {
	asq.predicates = append(asq.predicates, ps...)
	return asq
}

// Limit the number of records to be returned by this query.
func (asq *AuthStatesQuery) Limit(limit int) *AuthStatesQuery {
	asq.limit = &limit
	return asq
}

// Offset to start from.
func (asq *AuthStatesQuery) Offset(offset int) *AuthStatesQuery {
	asq.offset = &offset
	return asq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (asq *AuthStatesQuery) Unique(unique bool) *AuthStatesQuery {
	asq.unique = &unique
	return asq
}

// Order specifies how the records should be ordered.
func (asq *AuthStatesQuery) Order(o ...OrderFunc) *AuthStatesQuery {
	asq.order = append(asq.order, o...)
	return asq
}

// First returns the first AuthStates entity from the query.
// Returns a *NotFoundError when no AuthStates was found.
func (asq *AuthStatesQuery) First(ctx context.Context) (*AuthStates, error) {
	nodes, err := asq.Limit(1).All(newQueryContext(ctx, TypeAuthStates, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{authstates.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (asq *AuthStatesQuery) FirstX(ctx context.Context) *AuthStates {
	node, err := asq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AuthStates ID from the query.
// Returns a *NotFoundError when no AuthStates ID was found.
func (asq *AuthStatesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = asq.Limit(1).IDs(newQueryContext(ctx, TypeAuthStates, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{authstates.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (asq *AuthStatesQuery) FirstIDX(ctx context.Context) int {
	id, err := asq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AuthStates entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AuthStates entity is found.
// Returns a *NotFoundError when no AuthStates entities are found.
func (asq *AuthStatesQuery) Only(ctx context.Context) (*AuthStates, error) {
	nodes, err := asq.Limit(2).All(newQueryContext(ctx, TypeAuthStates, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{authstates.Label}
	default:
		return nil, &NotSingularError{authstates.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (asq *AuthStatesQuery) OnlyX(ctx context.Context) *AuthStates {
	node, err := asq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AuthStates ID in the query.
// Returns a *NotSingularError when more than one AuthStates ID is found.
// Returns a *NotFoundError when no entities are found.
func (asq *AuthStatesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = asq.Limit(2).IDs(newQueryContext(ctx, TypeAuthStates, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{authstates.Label}
	default:
		err = &NotSingularError{authstates.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (asq *AuthStatesQuery) OnlyIDX(ctx context.Context) int {
	id, err := asq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AuthStatesSlice.
func (asq *AuthStatesQuery) All(ctx context.Context) ([]*AuthStates, error) {
	ctx = newQueryContext(ctx, TypeAuthStates, "All")
	if err := asq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AuthStates, *AuthStatesQuery]()
	return withInterceptors[[]*AuthStates](ctx, asq, qr, asq.inters)
}

// AllX is like All, but panics if an error occurs.
func (asq *AuthStatesQuery) AllX(ctx context.Context) []*AuthStates {
	nodes, err := asq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AuthStates IDs.
func (asq *AuthStatesQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = newQueryContext(ctx, TypeAuthStates, "IDs")
	if err := asq.Select(authstates.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (asq *AuthStatesQuery) IDsX(ctx context.Context) []int {
	ids, err := asq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (asq *AuthStatesQuery) Count(ctx context.Context) (int, error) {
	ctx = newQueryContext(ctx, TypeAuthStates, "Count")
	if err := asq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, asq, querierCount[*AuthStatesQuery](), asq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (asq *AuthStatesQuery) CountX(ctx context.Context) int {
	count, err := asq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (asq *AuthStatesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = newQueryContext(ctx, TypeAuthStates, "Exist")
	switch _, err := asq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (asq *AuthStatesQuery) ExistX(ctx context.Context) bool {
	exist, err := asq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AuthStatesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (asq *AuthStatesQuery) Clone() *AuthStatesQuery {
	if asq == nil {
		return nil
	}
	return &AuthStatesQuery{
		config:     asq.config,
		limit:      asq.limit,
		offset:     asq.offset,
		order:      append([]OrderFunc{}, asq.order...),
		inters:     append([]Interceptor{}, asq.inters...),
		predicates: append([]predicate.AuthStates{}, asq.predicates...),
		// clone intermediate query.
		sql:    asq.sql.Clone(),
		path:   asq.path,
		unique: asq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		State string `json:"state,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AuthStates.Query().
//		GroupBy(authstates.FieldState).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (asq *AuthStatesQuery) GroupBy(field string, fields ...string) *AuthStatesGroupBy {
	asq.fields = append([]string{field}, fields...)
	grbuild := &AuthStatesGroupBy{build: asq}
	grbuild.flds = &asq.fields
	grbuild.label = authstates.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		State string `json:"state,omitempty"`
//	}
//
//	client.AuthStates.Query().
//		Select(authstates.FieldState).
//		Scan(ctx, &v)
func (asq *AuthStatesQuery) Select(fields ...string) *AuthStatesSelect {
	asq.fields = append(asq.fields, fields...)
	sbuild := &AuthStatesSelect{AuthStatesQuery: asq}
	sbuild.label = authstates.Label
	sbuild.flds, sbuild.scan = &asq.fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AuthStatesSelect configured with the given aggregations.
func (asq *AuthStatesQuery) Aggregate(fns ...AggregateFunc) *AuthStatesSelect {
	return asq.Select().Aggregate(fns...)
}

func (asq *AuthStatesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range asq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, asq); err != nil {
				return err
			}
		}
	}
	for _, f := range asq.fields {
		if !authstates.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if asq.path != nil {
		prev, err := asq.path(ctx)
		if err != nil {
			return err
		}
		asq.sql = prev
	}
	return nil
}

func (asq *AuthStatesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AuthStates, error) {
	var (
		nodes = []*AuthStates{}
		_spec = asq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AuthStates).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AuthStates{config: asq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, asq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (asq *AuthStatesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := asq.querySpec()
	_spec.Node.Columns = asq.fields
	if len(asq.fields) > 0 {
		_spec.Unique = asq.unique != nil && *asq.unique
	}
	return sqlgraph.CountNodes(ctx, asq.driver, _spec)
}

func (asq *AuthStatesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   authstates.Table,
			Columns: authstates.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authstates.FieldID,
			},
		},
		From:   asq.sql,
		Unique: true,
	}
	if unique := asq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := asq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authstates.FieldID)
		for i := range fields {
			if fields[i] != authstates.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := asq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := asq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := asq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := asq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (asq *AuthStatesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(asq.driver.Dialect())
	t1 := builder.Table(authstates.Table)
	columns := asq.fields
	if len(columns) == 0 {
		columns = authstates.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if asq.sql != nil {
		selector = asq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if asq.unique != nil && *asq.unique {
		selector.Distinct()
	}
	for _, p := range asq.predicates {
		p(selector)
	}
	for _, p := range asq.order {
		p(selector)
	}
	if offset := asq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := asq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AuthStatesGroupBy is the group-by builder for AuthStates entities.
type AuthStatesGroupBy struct {
	selector
	build *AuthStatesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (asgb *AuthStatesGroupBy) Aggregate(fns ...AggregateFunc) *AuthStatesGroupBy {
	asgb.fns = append(asgb.fns, fns...)
	return asgb
}

// Scan applies the selector query and scans the result into the given value.
func (asgb *AuthStatesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeAuthStates, "GroupBy")
	if err := asgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuthStatesQuery, *AuthStatesGroupBy](ctx, asgb.build, asgb, asgb.build.inters, v)
}

func (asgb *AuthStatesGroupBy) sqlScan(ctx context.Context, root *AuthStatesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(asgb.fns))
	for _, fn := range asgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*asgb.flds)+len(asgb.fns))
		for _, f := range *asgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*asgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := asgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AuthStatesSelect is the builder for selecting fields of AuthStates entities.
type AuthStatesSelect struct {
	*AuthStatesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ass *AuthStatesSelect) Aggregate(fns ...AggregateFunc) *AuthStatesSelect {
	ass.fns = append(ass.fns, fns...)
	return ass
}

// Scan applies the selector query and scans the result into the given value.
func (ass *AuthStatesSelect) Scan(ctx context.Context, v any) error {
	ctx = newQueryContext(ctx, TypeAuthStates, "Select")
	if err := ass.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AuthStatesQuery, *AuthStatesSelect](ctx, ass.AuthStatesQuery, ass, ass.inters, v)
}

func (ass *AuthStatesSelect) sqlScan(ctx context.Context, root *AuthStatesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ass.fns))
	for _, fn := range ass.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ass.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ass.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
