// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Doer-org/google-cloud-challenge-2022/infrastructure/ent/googleauth"
	"github.com/Doer-org/google-cloud-challenge-2022/infrastructure/ent/user"
	"github.com/google/uuid"
)

// GoogleAuth is the model entity for the GoogleAuth schema.
type GoogleAuth struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"refresh_token,omitempty"`
	// Expiry holds the value of the "expiry" field.
	Expiry time.Time `json:"expiry,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoogleAuthQuery when eager-loading is set.
	Edges GoogleAuthEdges `json:"edges"`
}

// GoogleAuthEdges holds the relations/edges for other nodes in the graph.
type GoogleAuthEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoogleAuthEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoogleAuth) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case googleauth.FieldID:
			values[i] = new(sql.NullInt64)
		case googleauth.FieldAccessToken, googleauth.FieldRefreshToken:
			values[i] = new(sql.NullString)
		case googleauth.FieldExpiry:
			values[i] = new(sql.NullTime)
		case googleauth.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type GoogleAuth", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoogleAuth fields.
func (ga *GoogleAuth) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case googleauth.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ga.ID = int(value.Int64)
		case googleauth.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				ga.UserID = *value
			}
		case googleauth.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				ga.AccessToken = value.String
			}
		case googleauth.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				ga.RefreshToken = value.String
			}
		case googleauth.FieldExpiry:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiry", values[i])
			} else if value.Valid {
				ga.Expiry = value.Time
			}
		}
	}
	return nil
}

// QueryUser queries the "user" edge of the GoogleAuth entity.
func (ga *GoogleAuth) QueryUser() *UserQuery {
	return (&GoogleAuthClient{config: ga.config}).QueryUser(ga)
}

// Update returns a builder for updating this GoogleAuth.
// Note that you need to call GoogleAuth.Unwrap() before calling this method if this GoogleAuth
// was returned from a transaction, and the transaction was committed or rolled back.
func (ga *GoogleAuth) Update() *GoogleAuthUpdateOne {
	return (&GoogleAuthClient{config: ga.config}).UpdateOne(ga)
}

// Unwrap unwraps the GoogleAuth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ga *GoogleAuth) Unwrap() *GoogleAuth {
	_tx, ok := ga.config.driver.(*txDriver)
	if !ok {
		panic("ent: GoogleAuth is not a transactional entity")
	}
	ga.config.driver = _tx.drv
	return ga
}

// String implements the fmt.Stringer.
func (ga *GoogleAuth) String() string {
	var builder strings.Builder
	builder.WriteString("GoogleAuth(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ga.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ga.UserID))
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(ga.AccessToken)
	builder.WriteString(", ")
	builder.WriteString("refresh_token=")
	builder.WriteString(ga.RefreshToken)
	builder.WriteString(", ")
	builder.WriteString("expiry=")
	builder.WriteString(ga.Expiry.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GoogleAuths is a parsable slice of GoogleAuth.
type GoogleAuths []*GoogleAuth

func (ga GoogleAuths) config(cfg config) {
	for _i := range ga {
		ga[_i].config = cfg
	}
}
