import { components, operations, paths } from "../openapi/openapi"

export type EState = components["schemas"]["EState"]
export type EStateCreate = components["schemas"]["EStateCreate"]
export type EStateList = components["schemas"]["EStateList"]
export type EStateRead = components["schemas"]["EStateRead"]
export type EStateUpdate = components["schemas"]["EStateUpdate"]
export type EState_EventRead = components["schemas"]["EState_EventRead"]
export type EType = components["schemas"]["EType"]
export type ETypeCreate = components["schemas"]["ETypeCreate"]
export type ETypeList = components["schemas"]["ETypeList"]
export type ETypeRead = components["schemas"]["ETypeRead"]
export type ETypeUpdate = components["schemas"]["ETypeUpdate"]
export type EType_EventRead = components["schemas"]["EType_EventRead"]
export type Event = components["schemas"]["Event"]
export type EventCreate = components["schemas"]["EventCreate"]
export type EventList = components["schemas"]["EventList"]
export type EventRead = components["schemas"]["EventRead"]
export type EventUpdate = components["schemas"]["EventUpdate"]
export type Event_StateRead = components["schemas"]["Event_StateRead"]
export type Event_TypeRead = components["schemas"]["Event_TypeRead"]
export type Event_UsersList = components["schemas"]["Event_UsersList"]
export type User = components["schemas"]["User"]
export type UserCreate = components["schemas"]["UserCreate"]
export type UserList = components["schemas"]["UserList"]
export type UserRead = components["schemas"]["UserRead"]
export type UserUpdate = components["schemas"]["UserUpdate"]
export type User_EventsList = components["schemas"]["User_EventsList"]