import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../../styles/Home.module.css'  
import { useState } from 'react'
import Link from 'next/link'
 

export default function Home() { 
  const [created, setCreated] = useState(false)
  return (
    <> 
      <Head>
        <title>募集画面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>募集する</h1> 
        <h2>イベント名</h2>
        <input /> 
        <h2>募集人数</h2>
        <input /> 
        <h2>詳細</h2>
        <input /> 
        <h2>場所</h2>
        <input /> 
        <button onClick={() => setCreated(true)} > 募集 </button>
        { created?  <Link href="/event?id=10">募集したイベント</Link> : <></>}
      </main>
    </>
  )
}
