import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'  
import { useState } from 'react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
  const [authed, setAuthed] = useState(false)
  return (
    <> 
      <Head>
        <title>ホーム画面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>サービス名未定</h1> 
        <a href="/debug"> {"> "} debug page</a>
        { 
          !authed 
          ? <>
              <button onClick={() => setAuthed(true)}>ログイン</button>
              <button>サインイン</button>
            </> 
          : <>
              <button><Link href="/event/create">募集する</Link></button> 
              <button onClick={() => setAuthed(false)}>log out</button> 
            </>
        }
      </main>
    </>
  )
}
