## Build
FROM golang:1.19 AS dev

WORKDIR /go/src/github.com/Doer-org/google-cloud-challenge-2022/server/src

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go install github.com/cosmtrek/air@v1.29.0

# air -c [tomlファイル名] // 設定ファイルを指定してair実行(WORKDIRに.air.tomlを配置しておくこと)
CMD ["air", "-c", ".air.toml"]