version: "3"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8081:8080"
    volumes:
      - ../openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
  