import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'  
import { useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
  const [isHost, setIsHost] = useState(false)
  const [hasJoined, setHasJoined] = useState(false)
  const event_id = useRouter().query.id;  
  return (
    <> 
      <Head>
        <title>参加フォーム画面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}> 
        <h1>参加フォーム画面</h1> 
        <div>event id: {event_id}</div>
        <button onClick={() => setIsHost((v) => !v)}>isHost : {isHost? "true" : "false"}</button>
        
        { 
          isHost 
          ? <> 
              <button>募集を締め切る</button>
            </> 
          : !hasJoined
            ? 
              <> 
                <h2>名前</h2>
                <input ></input> 
                <h2>ひとこと</h2>
                <input ></input>
                <button onClick={() => setHasJoined(true)} > 参加 </button>
              </> 
            : <>
                <h1>参加済みです</h1>
                <button onClick={() => setHasJoined(false)} > キャンセル </button>
              
              </> 
          
           
        }
      </main>
    </>
  )
}
