// Code generated by ent, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAuthenticated holds the string denoting the authenticated field in the database.
	FieldAuthenticated = "authenticated"
	// FieldGmail holds the string denoting the gmail field in the database.
	FieldGmail = "gmail"
	// FieldIconImg holds the string denoting the icon_img field in the database.
	FieldIconImg = "icon_img"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the user in the database.
	Table = "users"
	// EventsTable is the table that holds the events relation/edge. The primary key declared below.
	EventsTable = "user_events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldName,
	FieldAuthenticated,
	FieldGmail,
	FieldIconImg,
}

var (
	// EventsPrimaryKey and EventsColumn2 are the table columns denoting the
	// primary key for the events relation (M2M).
	EventsPrimaryKey = []string{"user_id", "event_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator func(int) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultAuthenticated holds the default value on creation for the "authenticated" field.
	DefaultAuthenticated bool
	// GmailValidator is a validator for the "gmail" field. It is called by the builders before save.
	GmailValidator func(string) error
	// IconImgValidator is a validator for the "icon_img" field. It is called by the builders before save.
	IconImgValidator func(string) error
)
