// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateAuthStatesRes interface {
	createAuthStatesRes()
}

type CreateEStateRes interface {
	createEStateRes()
}

type CreateETypeRes interface {
	createETypeRes()
}

type CreateEcommentRes interface {
	createEcommentRes()
}

type CreateEventRes interface {
	createEventRes()
}

type CreateGoogleAuthRes interface {
	createGoogleAuthRes()
}

type CreateLoginSessionsRes interface {
	createLoginSessionsRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteAuthStatesRes interface {
	deleteAuthStatesRes()
}

type DeleteEStateRes interface {
	deleteEStateRes()
}

type DeleteETypeRes interface {
	deleteETypeRes()
}

type DeleteEcommentRes interface {
	deleteEcommentRes()
}

type DeleteEventRes interface {
	deleteEventRes()
}

type DeleteGoogleAuthRes interface {
	deleteGoogleAuthRes()
}

type DeleteLoginSessionsRes interface {
	deleteLoginSessionsRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListAuthStatesRes interface {
	listAuthStatesRes()
}

type ListEStateRes interface {
	listEStateRes()
}

type ListETypeRes interface {
	listETypeRes()
}

type ListEcommentRes interface {
	listEcommentRes()
}

type ListEventRes interface {
	listEventRes()
}

type ListEventUsersRes interface {
	listEventUsersRes()
}

type ListGoogleAuthRes interface {
	listGoogleAuthRes()
}

type ListLoginSessionsRes interface {
	listLoginSessionsRes()
}

type ListUserEventsRes interface {
	listUserEventsRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadAuthStatesRes interface {
	readAuthStatesRes()
}

type ReadEStateEventRes interface {
	readEStateEventRes()
}

type ReadEStateRes interface {
	readEStateRes()
}

type ReadETypeEventRes interface {
	readETypeEventRes()
}

type ReadETypeRes interface {
	readETypeRes()
}

type ReadEcommentEventRes interface {
	readEcommentEventRes()
}

type ReadEcommentRes interface {
	readEcommentRes()
}

type ReadEcommentUserRes interface {
	readEcommentUserRes()
}

type ReadEventRes interface {
	readEventRes()
}

type ReadEventStateRes interface {
	readEventStateRes()
}

type ReadEventTypeRes interface {
	readEventTypeRes()
}

type ReadGoogleAuthRes interface {
	readGoogleAuthRes()
}

type ReadGoogleAuthUserRes interface {
	readGoogleAuthUserRes()
}

type ReadLoginSessionsRes interface {
	readLoginSessionsRes()
}

type ReadLoginSessionsUserRes interface {
	readLoginSessionsUserRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateAuthStatesRes interface {
	updateAuthStatesRes()
}

type UpdateEStateRes interface {
	updateEStateRes()
}

type UpdateETypeRes interface {
	updateETypeRes()
}

type UpdateEcommentRes interface {
	updateEcommentRes()
}

type UpdateEventRes interface {
	updateEventRes()
}

type UpdateGoogleAuthRes interface {
	updateGoogleAuthRes()
}

type UpdateLoginSessionsRes interface {
	updateLoginSessionsRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
