// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateEStateRes interface {
	createEStateRes()
}

type CreateETypeRes interface {
	createETypeRes()
}

type CreateEventRes interface {
	createEventRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteEStateRes interface {
	deleteEStateRes()
}

type DeleteETypeRes interface {
	deleteETypeRes()
}

type DeleteEventRes interface {
	deleteEventRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListEStateRes interface {
	listEStateRes()
}

type ListETypeRes interface {
	listETypeRes()
}

type ListEventRes interface {
	listEventRes()
}

type ListEventUsersRes interface {
	listEventUsersRes()
}

type ListUserEventsRes interface {
	listUserEventsRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadEStateEventRes interface {
	readEStateEventRes()
}

type ReadEStateRes interface {
	readEStateRes()
}

type ReadETypeEventRes interface {
	readETypeEventRes()
}

type ReadETypeRes interface {
	readETypeRes()
}

type ReadEventRes interface {
	readEventRes()
}

type ReadEventStateRes interface {
	readEventStateRes()
}

type ReadEventTypeRes interface {
	readEventTypeRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateEStateRes interface {
	updateEStateRes()
}

type UpdateETypeRes interface {
	updateETypeRes()
}

type UpdateEventRes interface {
	updateEventRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
